name: build-debian-common

on:
  workflow_dispatch:

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build image
        run: |
          sudo apt update && sudo apt install zstd extlinux -y
          yarn
          cd scripts && sudo ./build-debian.sh --image debian-common --dockerfile debian.common.Dockerfile --size 600 --memory 512  && cd ../
      - name: Release
        uses: actions/upload-artifact@v3
        with:
          name: debian-common
          path: |
            images/debian-common/linux.img.zst
            images/debian-common/state.bin.zst
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build image
        run: |
          sudo apt update && sudo apt install zstd extlinux -y
          yarn
          cd scripts && sudo ./build-debian.sh --image debian-python --dockerfile debian.python.Dockerfile --size 450 --memory 256  && cd ../
      - name: Release
        uses: actions/upload-artifact@v3
        with:
          name: debian-python
          path: |
            images/debian-python/linux.img.zst
            images/debian-python/state.bin.zst
