name: build-debian-common

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build image
        run: |
          sudo apt update && sudo apt install zstd extlinux -y
          yarn
          cd scripts/docker && sudo ./build-debian-common.sh && cd ../../
          sudo node ./scripts/build-state.js --image debian-common --memory 512 && sudo zstd -9 images/debian-common/state.bin -o images/debian-common/state.bin.zst
      - name: Release
        uses: actions/upload-artifact@v3
        with:
          name: debian-common
          path: |
            images/debian-common/linux.img.zst
            images/debian-common/state.bin.zst
